import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const allowPlaceholder = process.argv.includes('--allow-placeholder');
const sourcePath = resolve(projectRoot, '.env');
const outputPath = resolve(projectRoot, 'src/config/generatedEnv.ts');

function parseEnv(contents) {
  return Object.fromEntries(
    contents
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'))
      .map(line => {
        const separator = line.indexOf('=');
        return separator === -1
          ? [line, '']
          : [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

let values;
try {
  values = parseEnv(await readFile(sourcePath, 'utf8'));
} catch (error) {
  if (!allowPlaceholder || error?.code !== 'ENOENT') {
    throw new Error(
      'Missing .env. Copy .env.example to .env and add the Supabase project values.',
      { cause: error },
    );
  }
  values = {};
}

const supabaseUrl =
  values.SUPABASE_URL ||
  (allowPlaceholder ? 'https://placeholder.supabase.co' : '');
const supabasePublishableKey =
  values.SUPABASE_PUBLISHABLE_KEY ||
  (allowPlaceholder ? 'sb_publishable_placeholder' : '');

if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(supabaseUrl)) {
  throw new Error('SUPABASE_URL must be a valid https://*.supabase.co URL.');
}

if (!supabasePublishableKey.startsWith('sb_publishable_')) {
  throw new Error('SUPABASE_PUBLISHABLE_KEY must start with sb_publishable_.');
}

const generated =
  `// Generated by scripts/generate-env.mjs. Do not edit or commit.\n` +
  `export const env = Object.freeze({\n` +
  `  supabaseUrl: ${JSON.stringify(supabaseUrl)},\n` +
  `  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},\n` +
  `});\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, { mode: 0o600 });
console.log('Generated local Supabase configuration.');
