import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const allowPlaceholder = process.argv.includes('--allow-placeholder');
const environmentArgument = process.argv.find(argument =>
  argument.startsWith('--environment='),
);
const environment =
  environmentArgument?.slice('--environment='.length) ||
  process.env.CHOOSR_ENV ||
  'dev';

if (!['dev', 'uat', 'prod'].includes(environment)) {
  throw new Error(`Unsupported Choosr environment: ${environment}`);
}

const environmentSourcePath = resolve(projectRoot, `.env.${environment}`);
const legacyDevelopmentPath = resolve(projectRoot, '.env');
const outputPath = resolve(projectRoot, 'src/config/generatedEnv.ts');

function parseEnv(contents) {
  return Object.fromEntries(
    contents
      .split(/\r?\n/)
      .map(line => line.trim())
      .filter(line => line && !line.startsWith('#'))
      .map(line => {
        const separator = line.indexOf('=');
        return separator === -1
          ? [line, '']
          : [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

let values;
try {
  values = parseEnv(await readFile(environmentSourcePath, 'utf8'));
} catch (error) {
  if (environment === 'dev' && error?.code === 'ENOENT') {
    try {
      values = parseEnv(await readFile(legacyDevelopmentPath, 'utf8'));
    } catch (legacyError) {
      if (!allowPlaceholder || legacyError?.code !== 'ENOENT') {
        throw new Error(
          'Missing .env.dev (or legacy .env). Copy .env.dev.example and add the development Supabase values.',
          { cause: legacyError },
        );
      }
      values = {};
    }
  } else if (!allowPlaceholder || error?.code !== 'ENOENT') {
    throw new Error(
      `Missing .env.${environment}. Copy .env.${environment}.example and add the Supabase project values.`,
      { cause: error },
    );
  } else {
    values = {};
  }
}

const supabaseUrl =
  values.SUPABASE_URL ||
  (allowPlaceholder ? 'https://placeholder.supabase.co' : '');
const supabasePublishableKey =
  values.SUPABASE_PUBLISHABLE_KEY ||
  (allowPlaceholder ? 'sb_publishable_placeholder' : '');
const appVersion = process.env.CHOOSR_VERSION_NAME || '1.0.0';
const buildNumber =
  process.env.CHOOSR_VERSION_CODE || process.env.GITHUB_RUN_NUMBER || '1';
const phoneRecoveryEnabled =
  (values.PHONE_RECOVERY_ENABLED || 'false').toLowerCase() === 'true';

const isHostedSupabaseUrl = /^https:\/\/[a-z0-9-]+\.supabase\.co$/.test(
  supabaseUrl,
);
const isLocalDevelopmentUrl = (() => {
  if (environment !== 'dev') {
    return false;
  }

  try {
    const url = new URL(supabaseUrl);
    const isPrivateIpv4 =
      /^10\./.test(url.hostname) ||
      /^192\.168\./.test(url.hostname) ||
      /^172\.(1[6-9]|2\d|3[01])\./.test(url.hostname);

    return (
      url.protocol === 'http:' &&
      url.port === '54321' &&
      (url.hostname === '127.0.0.1' ||
        url.hostname === 'localhost' ||
        isPrivateIpv4)
    );
  } catch {
    return false;
  }
})();

if (!isHostedSupabaseUrl && !isLocalDevelopmentUrl) {
  throw new Error(
    environment === 'dev'
      ? 'SUPABASE_URL must be a hosted Supabase URL or a local/private HTTP URL on port 54321.'
      : 'SUPABASE_URL must be a valid https://*.supabase.co URL.',
  );
}

if (!supabasePublishableKey.startsWith('sb_publishable_')) {
  throw new Error('SUPABASE_PUBLISHABLE_KEY must start with sb_publishable_.');
}

const generated =
  `// Generated by scripts/generate-env.mjs. Do not edit or commit.\n` +
  `export const env = Object.freeze({\n` +
  `  environment: ${JSON.stringify(environment)},\n` +
  `  appVersion: ${JSON.stringify(appVersion)},\n` +
  `  buildNumber: ${JSON.stringify(buildNumber)},\n` +
  `  phoneRecoveryEnabled: ${JSON.stringify(phoneRecoveryEnabled)},\n` +
  `  supabaseUrl: ${JSON.stringify(supabaseUrl)},\n` +
  `  supabasePublishableKey: ${JSON.stringify(supabasePublishableKey)},\n` +
  `});\n`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, generated, { mode: 0o600 });
console.log(`Generated ${environment} Supabase configuration.`);
